# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-config
stringData:
  config.env: ENC[AES256_GCM,data:iDrp+roValgLzSdKuOiJSRtXmJvnZUssEd4y6wH0ZhLcbx0EFaPQr7HlSjiCACWs9QBsDiG0wb3KpOfr2ndpnFbd0fdAakA4P3RjQemKBEyModU=,iv:uSH7pwwEi0pKLZY5JSaGQKj41P+LbZ6bqMi/26puAN0=,tag:+4wuk3+FS/t45Ns4hHfxIQ==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:rl/xtA1kUggWlQcNx+Y=,iv:lbyA4M/A7s/F9oH673xVegPRp77iV+/8sT4VMMyV210=,tag:V4ILndLh0SkRujQpnqgluw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:ZF6FCezmRY8i4jwbD44=,iv:DQjMJk7jVLkrS/8j6d3JJzRLmvTGmJhiQLt+cp/Va3k=,tag:DaQ88e9Y5U6YhNmGsNFrnA==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScldlRVNydmxpNVJpazNp
        MXphVmRaZTFkcHQ5QjR5bEtuUHpjR0pjT0E0Ci93eHlkeGlwQkhiaHVxdFBRNHhs
        TkdOOXlFQjljc3JWSnptcXk1Vi90ODQKLS0tIEJ0dFh4TEFOOXVlVC9mWkJKRnRR
        bk1xNkJueWZSYm5ieUoxa0RoNkJyOUUKH5yRGzi5kUx8VbvDMc0ZzrobpXhH8rYI
        umfzHtl85qhlhdBVXalb1xlF8KsNjTtDAFNtymMGyywXkh2b04/GmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:QrvKQ3VOT6z4/jgo9Lm/ibTu6zS1OZ5Tyw8h4Mw/oiHK6jh8hHNA4GQnal2COvRqqb/mY6rbjM5qIV2ENYIshzbkuH6AdPqtZ3x1eZqx2GUknzh8gsB7ZlHsB4xoF0WRCJHtxvlr+4ITMgeeEewmW+KLzzp8qbYIH0tEbxkyL5g=,iv:TBqMawtbnYsSMXFTX8M3mNwC8SLIg9k/dZG9nAArqHk=,tag:jfxdqpSq/Mr1bxm3mk+KUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
