---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name minio
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: *name
  endpoints:
    - port: minio
      path: /minio/v2/metrics/cluster
