---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/minio.min.io/tenant_v2.json
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
spec:
  requestAutoCert: false
  configuration:
    name: minio-config
  pools:
    - name: default
      servers: 1
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
      volumesPerServer: 1
