# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg
stringData:
  username: ENC[AES256_GCM,data:iA2hwu1X3CD4KlbzaLI=,iv:XuVEdFSEivbAw4HOlgh73+ONe6yNzkWgIlaK9QtOMv8=,tag:lM7KZZwIViadGtnklv3+1g==,type:str]
  password: ENC[AES256_GCM,data:j/TriYXN6Np1COBmbnI=,iv:lsi/F48L8QsN0FdZXuOEhQS4UHSxc3ncEv5f/eC1BTg=,tag:5K5IS6lPAnsBKJ4dcJGlQw==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc1BmSld1clhnT0gvMzQv
        aWJrcGw4OS9DWEsyV0xRMTlWeUhCT3N2R3pzCmFTVnMyb0ZVcnRsRm45Rnc5SEUr
        M0FyRjI3dWRsTGp0ZnlHNXgyOHZ1VEUKLS0tIGpuYzZMMGtZa0FUNHFiZ0gzd3pU
        eWxKcTU4ZjBONDd6ZWJ2WTlDRFgxbzgKQlbTttuqcEd+M24ufT/aaylxIZrrZab8
        6K82L5eqBRiv5Zx9F3QhUk4AbdCq08FfXjZg9h7CL5I0Z/dnWv2jXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:clIjKQNr2KqhcccyiKtSZDMAo2KnwQ/P75eeVYzQIGxtSxtEjoKmu8bxpmubwvaeqgcpcM6r3Nmviagvnyk4lALHbeSGcrM1akvq4f9nG4xfu4Lv8bLbi9zzlGpBWE3MO9ADG9dmtNu8ULeAIXH6JyON5Vx+kICWcoIIyTMJlDE=,iv:3/nF0/C9tia9qH0WtwvH8Qx82ZWCRtGprRNlqWYcyHA=,tag:e4ML7INgYx34FHyoyWxHIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
