---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend-honyabookstore
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: honyabookstore
  path: kubernetes/app/base/backend/honyabookstore/
  dependsOn:
    - name: postgres-migration
    - name: minio-minio
    - name: backend-redis
  decryption:
    provider: sops
    secretRef:
      name: honyabookstore-sops-age
