---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: backend-honyabookstore
    includeSelectors: true
resources:
  - ./deployment.yaml
  - ./horizontalpodautoscaler.yaml
  - ./keycloak.secret.sops.yaml
  - ./minio.secret.sops.yaml
  - ./postgres.secret.sops.yaml
  - ./service.yaml
  # - ./servicemonitor.yaml
configurations:
  - ./kustomizeconfig.yaml
