# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: honyabookstore-minio
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:zlM85J7leG79QMQuUOY=,iv:FtC7R9YEGuJO+Y7lHFrbGjVWZeoaeQQdTSOPQLnr53o=,tag:qfSGd9eTG/Jg7SjND4a/1w==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:l544XaqS/tQIuBRgDT0=,iv:8D99y90ScyP54NQad5oKzdEPgLum312nnOZhCAPMfz4=,tag:uFNsrzNSq4CBoXT33gHDKQ==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWU00VzJKOGxVUGY5a21L
        RWRkeGpSbVJtdUJHK1lSS3AweDF6d092WXdVCkx1cUo1M0hQcjZ2VjJSOTFPc200
        dkhWSktCSHhJTlZQOFFDanlFWVRJb00KLS0tIDM0cHBSZEY3MUNYcDN3a3hCQ2tL
        VEd2WG40RklIMTQrQmpsYytWVW1iZUUKdZ3JdwejGYqS4bDeX84avoelAnJg5NJU
        wPNBaTcwom7XSZYQBgrPRAyGqP/QAOgTeXRNt8Z+p2+9YuASwkvEZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:+txbVTgfVxWaiDrP6nnXy+JMg2F88SOyTo/KGwgdgqE/fA+Ol44kWDqGWcLL4EluUC5DObiuHpvlbJuTOiHWsy7lUJy6F8orNNmx05E0eI5PfvWpmrbTHAAfDhLgLgGqq3gy9pBgDHeM7/yIG0H639BUc5UgETUde6hk+BHOtlk=,iv:rSwU+9WkBPxvJTsJGa0ku9pAlPPCBlFCKw+yz3+ZMV4=,tag:/OBPp5ivO6W6Q+/r8kREsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
