# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: honyabookstore-postgres
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:wNeOIR9gCoOWhPO1o2o=,iv:4qjxEs+BKEp1DZJIvsSlZoTw0Yj3w1ygeSiMM6pgNhw=,tag:SSygO04BrZOZDMFbZ6Wj8A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:m5Mu0H9fSzks+FATpro=,iv:IW064zXq0wG4CERfTzQ+8XIFT3pLyhqeDnJ8uATHslg=,tag:UcymmpHTGgZ3wFNZX8Lm/Q==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMWxBVWtWQS9qSFNaL0la
        M3dtdzhMQnpSVWFFNXZDNVFSYkdZaHlJbkVZClIvd2gvOWtJbjlNbkdBN1M0cTZO
        eWozYlpOSDdkWlk0M1RLQU5rWjBnY2cKLS0tIE9qLzJxcCthbnFMS3JaZnJsTVJi
        cStPVDliKzBVZ24wNnJ1MXk2REpLRUkKnEzOASioGYTBGM4N/nFVuSnZibugNWoj
        xYH9Iiub5F1wMGY3x+MkjPB5coTQ4nBZ0iX4gFy/LhvIdpmukwIPwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:rmymMrF2cf9mnIbHhAaM60lcdShwORPlbDn0OMvshz9gdW8qjAv699FWTqUNFQptVnPwyuhqIYhaEpQw/xDaBYzlaE0+8kCbeNoHdrPEcorb4y4Po4kV2iWwb9tWcgxPzBfl0bhAUxgi8Nqu1lM2whZpGXiyazCqLm/ymuEC0nc=,iv:WvxlXx7GdQE+v1hHRGAUcGpFb3wVLLPOp7kIHMJO5Lc=,tag:3wYc3+zwnB/vwB1wjGmMsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
