---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: honyabookstore
spec:
  interval: 30m
  timeout: 1m
  ref:
    branch: main
  url: https://github.com/honya-bookstore/infrastructure
