# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: honyabookstore-honyabookstore
stringData:
  VNP_SECURE_SECRET: ENC[AES256_GCM,data:kRZrOLPPK7j2pRDugoToEpWmBfJTsAh4xcmIj+ehr+Q=,iv:O5ZStguuaTaD9LveZhCpFt7JgnNn92eOhMHoIoyjWcY=,tag:2rkJfjvh+W53AtbEqbxbEA==,type:str]
  VNP_TMN_CODE: ENC[AES256_GCM,data:jYTuwVtAZ1U=,iv:/sG1UhM79W0pFF212Fn6iABn7hcrrMkemqdDvHDI6D8=,tag:y5IOC9W6CfZU8dMn3YJAvQ==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UkEyRUM3UTlCV29DYyt2
        WmhmN0g5QWtJNDNtYTBrbzR0cThnS2UvM1hJCk1jcU55OGM5bXVqUFd1WXhrbDIz
        TzFzVURtWm9YaGdYRCtCakEyc3lPU2MKLS0tIGl2RDEvd2U2YnlYampmOFM4aUQ1
        UmcrenFvMnlIcWV3cnlFdnpoUUNSVFkKOBhjHUNyFDEDEqEhNAtltPCG0bIx7vGD
        UUdTOrelusctLkWcR9UD1wkyjXAXDzk3KPtsrH3tgXeDwzOwLI1w0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T04:20:00Z"
  mac: ENC[AES256_GCM,data:gVp8iHqo3uUkAcwlkD2+/UiMP5CEeuQ8cX2VP4YCT1W9nmxUvelxX8NYp4YgbJhuXtN5tWPQDxQHfueNck8B6OW5kFZsHedl/XxRRZnEi1VzuTYrWLeE0bXxqrKB9jIrDQzcL/rGbqOGoO1doh49mbmbEp/5BUANhGJuUTPKrGs=,iv:CQzA9LHuz40q1DM/eedHtTk4Box0d39TSDSB0PLFpu8=,tag:APZ5Ie8/q7dZo4MjZjiCmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
