# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: honyabookstore-keycloak
stringData:
  KC_CLIENT_SECRET: ENC[AES256_GCM,data:OWpdx/kHqrC/pkGqWKg=,iv:7SwLVAGxwWIu9OJxDQ8S4U/3/pfrEgkJtdzYpoMWgZo=,tag:kFjuEpQ3fwl2ulRzYr6N2A==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RksvaXYrS0djeWlnbVQ4
        VnBBZlRQL3AwZGlNOWZsSWpuL3piY1NSMGtjClR6Qi8wN2lrOEZSWmV5eFc1dWNF
        UkNxZ0VpZHRKNStJd2VlR21UdTJNUFEKLS0tIFRYTkFyUzQ4bUx6L1ZNK2JIaDhP
        RDRPN0NVVUdUN2RGRTZnOVpERko3Sk0KIWmCtXWhT2XPNIsrf914kNWCBDXn5Fpo
        vgchUZFAjHOeEqm8wDiZnUmoHQ2mOXDt80aPC0xROykYfYH4/StMHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:NMoDyxvBalDrLA2ON7qCUxJ1cbFKkyeXCsJ+RpvtwVH9JrcdXK4KzQqLWtxKxl8/fr8JDWpPoHInMwvgS24/VFoBdt6qrHwFf4JUMRU4dJooo7G34Dhp47ThQRtezkhefX4LilD8qNf9HkRi/F2Eu7YquBQDqw+g7bseXnK4oy0=,iv:4l4FqsGKGA1dmyfia5zuEeLD6NHOzMlhmVtJQJ05K4U=,tag:KUmPozUWQLo+EiZXOCjYBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
