# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: setting
stringData:
  IDVN_DOMAIN: ENC[AES256_GCM,data:7ykIGn6/N+kN2OmWZGk27g==,iv:EYWHvxDRA9lmO3uWfuGguXQZvhfdpn7KmR8CkpJK1+4=,tag:AoGiuuiE7ZVUgPHLn3DzdQ==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidkY4bTRuOE81MEsvMHVE
        eVR1dGR2M1ZqQm5ydW1aZjdqNHMxRXdvM3dVClIzRmYwQmlHZkxzT25xZkJPdUdy
        NmEzcUY2cnByamplamwxL2Y3T2k0SHMKLS0tIENSQkZZTGlkd2hYQUQ0dXl5ZzVR
        a0Q3N3RwSzU2cVNRN25Nc1pBK0kwT28KOdjwWS5dNUUNqBJOFJSUF77ooMfTiwlO
        IpzxgzegdhKIm+btFjWU0qcfRGynJfd8DUg6Qv/dKNhexh7mJkvSmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:xY4yBy5d00J2Wo9wDnfw/etDFfnHwrMiJAO4zf/v582+SkGu8FLRjVtAIL5IW8ax8A257VFz5Mpeug6yhCiTshTbARQ4S5yTG5LGbuil/dwPKDic+rJgTFXwrBFDsYSTgRBNbRcnSPciNX8zjwFjwgEk3NNb3RA9wDgBHKxFq/Y=,iv:M3B6C4EKdvjlGv5jh5CZ3847cyOHFXx3fH0YdrDpdsg=,tag:AiJTobSKGJk/RI74UzoGuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
