---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name honyabookstore
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      containers:
        - name: *name
          image: ghcr.io/honya-bookstore/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_ENDPOINT
              value: honyabookstore.backend
            - name: AUTH_KEYCLOAK_ID
              value: frontend
            - name: AUTH_KEYCLOAK_ISSUER
              value: https://keycloak.example.com/realms/honyabookstore
          envFrom:
            - secretRef:
                name: honyabookstore-keycloak
            - secretRef:
                name: honyabookstore-honyabookstore
          # readinessProbe: &health
          #   httpGet:
          #     path: /api/health
          #     port: 3000
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   <<: *health
          #   periodSeconds: 10
          #   failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits:
              cpu: 500m
              memory: 600Mi
  selector: {}
