# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: honyabookstore-honyabookstore
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:RLn/VzFbi3w3oQ0NwC0MCLtYDqlDKQuK5yc7pjCF9EE5Bq7T538Chk1zfEE=,iv:6Ba7B4wyPGSsLLUNbB6ffLDf6+9jbHJ+h2V91+ghhu8=,tag:pieCZeMy//nSXlaL7756Ow==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnamFzV1Vkd09maFIyVG53
        VjQ4UENHWHpHZ0JtaU5ZdFo3WkJ5KzN0WlZNCmlmYXRnTXNadFN3NWdzbFkzdVVN
        QWZ4WE5WanQwM0JYdkhLZEM0ZE9ZdVUKLS0tIFYrUDByd2svWkV0NGtZRzBvRmtr
        RTFWTEZBNDZOcVQ2bW0vMzd6aE9seHcKUJOi0iTUkMKE4HUP13Ypf+/pzllrTL3z
        s6zdXZUwTUp0U5vdjqSWzSpL5yTiuvV9C3DWhlfOhk4y8+YWLgyqpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:Ge5It92840LJEJcDoz3Jsc0vN7ZfSU1aKh2Rgy3swIxrNJqP56p0aJAL7+RgG8WbsqYQomPSXRROWYL+OqaV4jrfNbt5J4E4trz+dzsH42+dK1pT8ph2A6Fz39E6+jfqDJSd6NrOBL3EBN0WK0lwQh0JOLSAmbwf2bm4YcrOqIo=,iv:tU9zeaUBAzkbVh6d2KsI2rweItieEhLebQFt5A9dGdo=,tag:tOCvebsCNr1y3JTZSj1c4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
