---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-migration
  labels:
    flux.kevinnitro/substitute: "0"
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  wait: true
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: honyabookstore
  path: kubernetes/app/base/postgres/migration/
  dependsOn:
    - name: postgres-cnpg
