---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/job-batch-v1.json
apiVersion: batch/v1
kind: Job
metadata:
  name: &name create-bucket
spec:
  template:
    spec:
      containers:
        - name: *name
          env:
            - name: MINIO_API_URL
              value: http://minio.honyabookstore-dev-minio:80
