---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/job-batch-v1.json
apiVersion: batch/v1
kind: Job
metadata:
  name: &name create-bucket
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: *name
          image: minio/mc:latest
          command:
            - /usr/bin/bash
            - -c
          args:
            - |- # language: bash
              set -euo pipefail

              mc alias set local ${MINIO_API_URL} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
              mc mb local/honyabookstore || true &&
              mc anonymous set public local/honyabookstore
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-config
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-config
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_API_URL
              value: http://minio.minio:9000
