---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/receiver-notification-v1.json
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: webhook
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook
  resources:
    - kind: GitRepository
      name: &honyabookstore honyabookstore
      namespace: *honyabookstore
