# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: webhook
stringData:
  token: ENC[AES256_GCM,data:rQhLkM+tAni1eP6+QaZNVOz7MTjzVFQMnKIMB6bBnUrIARc5bRCskmk+7oo=,iv:9whBzKulVY7i7XGu6P3JwjKoAayqd9zv/fcf1FJ9B2U=,tag:y0QNG92fqXBRb5tRX+s5zw==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UGZnK0RqcDFHQU4rb1FZ
        ZXF5cUgyTHF5cEJiZUU5czB3MERSSEVtYlhRClRZNjdCTnIzUzhHU2ZZTDVyK1pV
        amw4amVsN3dPeng3b0pNeFNFRmR4TFUKLS0tIEtXN2JubjJRUUE3YXpBWkRlS1pN
        TUxIRGorbHgzd1ZzNVZWbW1URm1ISE0Kxl5RxwYPMUGH+uZRmVHy2zvVPSS3X+nG
        fszYuoBykMWEvoYZFCCVxgEjDpuZlrz5WQ1AQuDkda9rnQihImswlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T04:50:01Z"
  mac: ENC[AES256_GCM,data:lByqW/os1B4quwfGjmLecGMT5+wCNX9N9pgLN/gTXcjwsMtJooCW1AGmDoM18dQv01Qugxc+fWnPsCZArrn1SlneyaKUkSWVpI2ICP0WgkYz9ZCHYyLpKmLgC5NR2Q3QwsEMpjzB8vjXRgDvRIlAFnOQI9b+WHoGGXNRDNpCHxE=,iv:MifpPOSolG7UhrWulD/HKNs4scnJNw2be7BX57l11tc=,tag:BafULWTiXwDvNasgN+bQVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
