---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name honyabookstore
spec:
  template:
    metadata:
      labels:
        alloy.kevinnitro/scrape: "1"
    spec:
      containers:
        - name: *name
          env:
            - name: BACKEND_ENDPOINT
              value: honyabookstore.honyabookstore-dev-backend
            - name: AUTH_KEYCLOAK_ISSUER
              value: https://keycloak.${IDVN_DOMAIN}/realms/honyabookstore-dev
