# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: honyabookstore-keycloak
stringData:
  AUTH_KEYCLOAK_SECRET: ENC[AES256_GCM,data:h84cW9Cqraac/Fiy9SY=,iv:gEQVVK5mr7tuGl0ikA7dChQqgahO353uymKnvMAlrbU=,tag:06lucjDIMMBB4T8woeT+ng==,type:str]
sops:
  age:
    - recipient: age1wd52pjevau9p02g4e04h9nkpplyt4xq3la5xxe3arepjhxspl39qacr2vs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydkJqa3N1TGV6cXV1cTgz
        ckl0ZGxlcHF1R0M3c01HUy9DTnd4dEJlV2xFCmQwTUNldlJZVm9kcUxyWHJVL3p3
        OGkvL0kxNEdvOHYwdkJSaUgrUUpHY2sKLS0tIE1QM0VJVHFPVk52R3dFYTAyRk8v
        dzFkRzdhL3llSm9nZ3JKVXFTRVNFWTgKBWpC53Riyc8u8eNsbaDhgpQxZVrhiYRQ
        rZ0Q8+R1eqsDW0FT1fsuBhGVE746tWA9et9ixxl8OHzkHrzt0POeng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T06:09:29Z"
  mac: ENC[AES256_GCM,data:yBMv32syfe/XlEeTEVyjclDs7mOuYxA+5TSlcCQtXb4GvnMcVC6XjC2F88dSsMSq0+lJevZ2RrcBZEMXwjHCj7Ce4zoRIhVukcGLl1gFNItSOZoufFmlC0s9BPCQvRuSoFusNn3pnoirDFOUItkNQL0NqtztUkTKQxy17sktX/c=,iv:EbpcR88wWNrp8CHjxY+gVhLTBSZGpIArfrv7Uha6lR4=,tag:GBPBbw7LVC524Eq7ckizmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
