name: Update Image

on:
  repository_dispatch:
    types:
      - renovate

concurrency:
  cancel-in-progress: false
  group: update-image

env:
  renovate-version: "41.169"

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      IMAGES: ${{ github.event.client_payload.images }}
      ENVIRONMENTS: ${{ github.event.client_payload.environments }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Show received payload
        run: |
          echo 'Received image: ${{ env.IMAGES }}'
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.ORG_BOT_PRIVATE_KEY }}
          app-id: ${{ vars.ORG_BOT_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: infrastructure
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-renovate-${{ env.renovate-version }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          token: ${{ steps.get_token.outputs.token }}
          configurationFile: renovate/action-renovate-config.js
          renovate-version: ${{ env.renovate-version }}
        env:
          RENOVATE_GITHUB_REPOSITORY: ${{ github.repository }}
          RENOVATE_GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          RENOVATE_PLATFORM_COMMIT: "true"
          RENOVATE_TARGET_IMAGES: ${{ env.IMAGES }}
          RENOVATE_TARGET_ENVIRONMENTS: ${{ env.ENVIRONMENTS }}
